### PR TITLE
Release working version

### PR DESCRIPTION
**Pull request by mikz**
Hi, this is working version of github integration. We are using it for some time in production.

### CODE REVIEW

**Comment by tommygnr** [comment]
:+1:

**Comment by jrochkind** [comment]
@mikz is this still working?  How about releasing with a different gem name? I'm interested in a working integration.

**Comment by jrochkind** [comment]
@mikz Awesome. Would you be interested in 'forking' and releasing as an actual gem, so I can use it too? :)   Since the maintainer here seems to be MIA. 

Right now I guess I'd have to use it from your branch directly from github, I'd love to have an actual gem release.  Oh, I guess this _original_ may not have been released either! If you wanted to release it, could maybe call it "capistrano-github-releases" or something. 

If you really don't want to release and take responsibility for a gem... I guess I might be forced to if I really want to use it.

**Comment by mikz** [comment]
@jrochkind It has been forked and released 3 years ago. https://github.com/3scale/capistrano-github

https://rubygems.org/gems/capistrano-github/versions/0.1.1 is the latest release.

**Comment by jrochkind** [comment]
Ha, awesome, thank you! You are my hero!   This repo is what I got to googling, I hadn't found your forked released version. 

Well, now this is here for whoever else finds this googling!

I am not sure who the maintainer of _this_ repo is, to tag them, but it seems like ideally they should just delete this repo now, since this is an abandoned not working version of what you have working and released in a different repo, and finding it googling is just a distraction.

**Comment by jrochkind** [comment]
@mikz I notice there's no way to file issues on your repo, as it's a fork. You might want to click the button that has GH treating it as an independent thing instead of a fork of this abandoned repo, so it's got an Issues tab. 

If i could file an issue, I'd recommend replacing the README instructions to "Add this line to your application's Gemfile: `gem 'capistrano-github', github: '3scale/capistrano-github'`", to use the actually releaesd version as would be more standard, `gem 'capistrano-github', ">= 0.1.1"`.  And/or to actually release a 1.0, since it's been working great for you in production for a couple years now.

**Comment by mikz** [comment]
@jrochkind you can open Issues now. But if you have suggestions for the README, then I'd rather see a PR 😆 It has been very low touch project for years and I don't really plan to do any work there.

**Comment by jrochkind** [comment]
okay cool! If I get around to using it, I may give you a PR for tagging it 1.0. Alas, you'd still have to do the `rake release` to get it to rubygems, can't do that for you (unless you wanna give me rubygems release rights too)

**Comment by will-in-wi** [comment]
Closing this per https://github.com/capistrano/github/issues/9 in favor of https://github.com/3scale/capistrano-github. Future issues should be sent there.

**Pull request closed without merging**
